<a href="https://colab.research.google.com/github/nicholasfurl/Great-Courses/blob/main/Lesson04_neuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
from sklearn.datasets import fetch_openml
#I guess these are pandas format. Doc says it opens bundle but
#X is DataFrame type with Value field describing pixel1, pixel 2 etc with 7000 values each
#y is Series type with 7000 entries and one number for each entry (presumably labels)
#plus y has Name field and appears to be defining nine categories stored in strings?
#This seems to take a long time to run.
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
print(X)
print(y)

       pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel7

In [54]:
#Lesson doesn't like panda dataframe and wants to convert to numpy array
#Presumably I need to import numpy for this
import numpy as np
X = np.array(X)
y = np.array(y)
print('X: '+str(X.shape)+'\n'+str(X))
print('y: '+str(y.shape)+'\n'+str(y))


X: (70000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
y: (70000,)
['5' '0' '4' ... '4' '5' '6']


In [55]:
#Looks like lesson wants to randomise the rows / stimulus order

#Not sure how I feel about having to import every single thing from a completely different course. Lots to have to memorize.
from sklearn.utils import check_random_state

#RandomState type. 0 appears to be the seed (are 0 and None equivalent?)
random_state = check_random_state(0)
print('random_state: '+'\n'+str(random_state))

#Appears to be a 7000 element column (nd array) of random numbers. I can do this with one line in matlab without importing anything or creating extraneous objects. An improvement?
permutation = random_state.permutation(X.shape[0])
print('permutation: '+str(X.shape)+'\n'+str(permutation))


random_state: 
RandomState(MT19937)
permutation: (70000, 784)
[10840 56267 14849 ... 42613 43567 68268]


In [56]:
#This seems relatively transparent but don't forget things you've learned about Python:
#You can index the rows of an adarray without mentioning the columns (hence one number for index)
#reshape has this -1 which will automatically compute the size of the remaining (fully determined) dimension after you've specified the rest already.

#Randomise rows / stimuli in X (pixels) and y (labels) and then reshape X so that ?? It looks the same to me
X = X[permutation]
y = y[permutation]

print('X before reshape: '+str(X.shape)+'\n'+str(X))
X = X.reshape((X.shape[0], -1))
print('X after reshape: '+str(X.shape)+'\n'+str(X))


X before reshape: (70000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
X after reshape: (70000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [50]:
#This sample code keeps redefining X and y and I worry they will not be correct if I need to rerun blocks. 
#In case I want to start over, apparently this code will delete all variables in "workspace"
#Except apparently the obj iterator I create here (which, by the way, is for some reason a str!)
#Ignore this when running ML lesson

objects = dir()
for obj in objects:
  if not obj.startswith("__"):
    del( globals()[obj] )


In [58]:
#So far sklearn has had .datasets, .model_selection and .utils plus function names within these to learn
from sklearn.model_selection import train_test_split

#From the doc on train_test_split, it appears the randomisation can be done by this function instead of doing it above (maybe?)
#Doc also says this takes pandas DataFrames - did we need to convert to nparray?
#From the doc, I wonder if python allows the arguments to be entered in any order, provided they have the right variable names?
#Also, from the doc, I think you only need to specify train_size or test_size unless their sum doesn't equal the number of observations
train_samples = 5000
test_samples = 1000
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=train_samples, test_size=test_samples)